### ISSUE TITLE
Endpoint to get package name from log IDs

### ISSUE THREAD

**Issue by calvinrp** [bytecodealliance/registry#227]
In order for registry mirrors to have the ability to list package names, we need to add an API endpoint to retrieve the package names. A registry may delist packages and choose to not provide the package name.

By requesting the registry ledger data, federating registries can observe the `logId`s of each package. This issue proposes adding an endpoint to `POST` a list of `logId`s and retrieve the corresponding package names.

**Comment by lann** [comment]
One thing we had discussed was making this part of a new set of "query" endpoints. The distinction here to me is that all other endpoints to date are working with verifiable append-only data while this one allows mutations.

...which is a little bit weird right now because logIds are generated just by hashing the log name... :thinking:

**Comment by calvinrp** [comment]
> One thing we had discussed was making this part of a new set of "query" endpoints. The distinction here to me is that all other endpoints to date are working with verifiable append-only data while this one allows mutations.
> 
> ...which is a little bit weird right now because logIds are generated just by hashing the package name... 🤔

I don't recall discussing renaming packages. I assumed that is out of scope for this change. 

This change just allows a `LogId` to `PackageName` lookup. If you want the `LogId` from a `PackageName`, it is computed using the hashing implementation in the code.
