### ISSUE TITLE
Check in `build.rs` if the required `protoc` version is available

### ISSUE THREAD

**Issue by Kylebrown9** [bytecodealliance/registry#86]
Use [`protoc_from_env`](https://docs.rs/prost-build/latest/prost_build/fn.protoc_from_env.html) to find the `protoc` that prost will use and then run the version command to check if version `3.15` or greater is available.

**Comment by Gearme** [comment]
I had a look at this and it turned out to be a little more tricky than I'd expected. [protobuf's versioning scheme](https://protobuf.dev/support/version-support/) these days actually has runtime-specific major versions, with protoc _itself_ not being semver.org compatible: protoc's versioning only has two dot-separated version numbers (plus the rc) these days rather than three.

`$ protoc --version` may therefore look like `libprotoc 3.12.4` or like `libprotoc 23.0-rc2` depending on the version - and with 20.x being >3.15, both will need handling.

**Comment by Kylebrown9** [comment]
Thanks for taking a look, that does sound inconvenient.
Thinking of giving it a go?
